### PR TITLE
Remove forbidden code from the NetO11y tracer

### LINKED ISSUE #673: Crash on start up
After the merge of https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/529 pods in are failing to start with the following logs 

time=2025-09-23T14:24:33.848Z level=INFO msg="OpenTelemetry eBPF Instrumentation" Version=main Revision=bbe6af3 "OpenTelemetry SDK Version"=1.37.0
time=2025-09-23T14:24:33.875Z level=INFO msg="got host ID" component=ContextInfo func=fetchHostID fetcher=AWS hostID=i-0a0a3a3b6cd5d6baf
time=2025-09-23T14:24:33.875Z level=INFO msg="starting Beyla in Network metrics mode"
time=2025-09-23T14:24:33.875Z level=INFO msg="initializing Flows agent" component=agent.Flows
time=2025-09-23T14:24:33.875Z level=INFO msg="starting Application Observability mode"
time=2025-09-23T14:24:33.875Z level=INFO msg="using socket filter for collecting network events" component=agent.Flows
time=2025-09-23T14:24:33.875Z level=INFO msg="waiting for K8s metadata synchronization" component=kube.CacheSvcClient timeout=30s
time=2025-09-23T14:24:33.903Z level=INFO msg="using hostname" component=traces.ReadDecorator function=instance_ID_hostNamePIDDecorator hostname=10-41-198-220.datadog.datadog-system.svc.cluster.local
time=2025-09-23T14:24:33.908Z level=INFO msg="using hostname" component=traces.ReadDecorator function=instance_ID_hostNamePIDDecorator hostname=10-41-198-220.datadog.datadog-system.svc.cluster.local
time=2025-09-23T14:24:33.909Z level=INFO msg="Starting main node" component=obi.Instrumenter
time=2025-09-23T14:24:33.909Z level=INFO msg="starting span cloner" component=SpanCloner
time=2025-09-23T14:24:33.909Z level=INFO msg="opening prometheus scrape endpoint" component=connector.PrometheusManager port=9090 path=/metrics
Error Log:
 BPF_STX uses reserved fields
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
time=2025-09-23T14:24:33.914Z level=INFO msg="exiting auto-instrumenter" component=obi.Instrumenter
time=2025-09-23T14:24:33.914Z level=INFO msg="context done. terminating span cloner" component=SpanCloner
time=2025-09-23T14:24:33.915Z level=ERROR msg="closing metrics provider" component=MetricsReporter error="context canceled"
time=2025-09-23T14:24:33.915Z level=INFO msg="K8s cache service connection lost. Reconnecting..." component=kube.CacheSvcClient error="error receiving message: rpc error: code = Canceled desc = context canceled"
time=2025-09-23T14:24:37.337Z level=ERROR msg="OpenTelemetry eBPF Instrumentation ran with errors" error="setupNetO11y: can't start network metrics capture: loading and assigning BPF objects: field ObiSocketFilter: program obi_socket__filter: load program: invalid argument: BPF_STX uses reserved fields (1 line(s) omitted)"

### PR DESCRIPTION
**Pull request by rafaelroquetto**
Linux kernels < 5.11 do not properly support atomic instructions, with the exception of the now legacy `BPF_XADD`, which means only `__sync_fetch_and_add` instructions whose return value is discarded is allowed.

This PR addresses that by refactoring the neto11y ebpf code to only rely on the allowed instructions. This is achieved by initialising the flow only once when its associated storage is initialised.

Tested on Debian 11 5.10.0-35-amd64

Resolves #673

### CODE REVIEW

File: bpf/netolly/flows_common.h [hunk 1]
```diff
@@ -43,6 +43,8 @@
 
 #define INITIATOR_UNKNOWN 0
 
+#define INITIATOR_UNSET 255
```
Comment (rafaelroquetto) [inline bpf/netolly/flows_common.h:46]: This will be refactored as an enum in a subsequent PR - keeping it consistent for now.

File: bpf/netolly/flows_common.h [hunk 2]
```diff
@@ -571,34 +533,17 @@ static __always_inline int flow_monitor(struct __sk_buff *skb) {
 
     __sync_fetch_and_add(&aggregate_flow->bytes, skb->len);
     __sync_fetch_and_add(&aggregate_flow->packets, 1);
```
Comment (rafaelroquetto) [inline bpf/netolly/flows_common.h:516]: These are allowed - they correspond to the legacy `BPF_ADD` atomic ops.

File: bpf/netolly/flows_common.h [hunk 3]
```diff
@@ -571,34 +533,17 @@ static __always_inline int flow_monitor(struct __sk_buff *skb) {
...
 
-    // initialise flow
-    atomic_min_u64(&aggregate_flow->start_mono_time_ns, current_time);
-    aggregate_flow->iface_direction = get_flow_direction(&id, flags);
-    aggregate_flow->initiator = get_connection_initiator(&id, flags);
-
-    // mark flow as fully initialised
-    __sync_lock_test_and_set(&aggregate_flow->init_state, k_flow_initialized);
+    if (aggregate_flow->initiator == INITIATOR_UNSET) {
+        aggregate_flow->initiator = get_connection_initiator(&id, flags);
```
Comment (rafaelroquetto) [inline bpf/netolly/flows_common.h:542]: ditto

File: bpf/netolly/flows_common.h [hunk 4]
```diff
@@ -571,34 +533,17 @@ static __always_inline int flow_monitor(struct __sk_buff *skb) {
...
+    }
 
-    if (must_submit(aggregate_flow)) {
-        submit_flow(&id, aggregate_flow);
+    if (must_submit(aggregate_flow->start_mono_time_ns, current_time, flags)) {
```
Comment (rafaelroquetto) [inline bpf/netolly/flows_common.h:518]: start_mono_time is set when the element is initialised in the map, so that's safe - current_time and flags are also actual, so issues here.

File: bpf/netolly/flows_common.h [hunk 5]
```diff
@@ -571,34 +533,17 @@ static __always_inline int flow_monitor(struct __sk_buff *skb) {
...
+        submit_flow(&id, aggregate_flow, flags);
```
Comment (rafaelroquetto) [inline bpf/netolly/flows_common.h:519]: whilst highly unlikely, this may end up being called twice - the only scenario where this is possible entails a flow about to expire and a concurrent packet containing any termination flags

File: bpf/netolly/flows_common.h [hunk 6]
```diff
@@ -315,17 +258,24 @@ static __always_inline u64 get_rb_flags() {
...
 
-static __always_inline void submit_flow(const flow_id *id, flow_metrics *metrics) {
-    bpf_map_delete_elem(&aggregated_flows, id);
+static __always_inline void submit_flow(const flow_id *id, flow_metrics *metrics, u16 flags) {
+    // whilst highly unlikely, it is theoretically possible for submit flow to
+    // push duplicates - this is mitigated by the call to bpf_map_delete_elem
+    // (1) which causes subsequent calls to bpf_map_lookup_elem (2) to fail -
+    // the actual aggregated_flows value is ref-counted by the kernel and
+    // remains valid until the event is submitted
+    if (bpf_map_lookup_elem(&aggregated_flows, id) == NULL) { // (2)
```
Comment (rafaelroquetto) [inline bpf/netolly/flows_common.h:305]: this is an attempt to mitigate the already unlikely duplicated flows - when line 278 hits, this will return NULL.

It is still theoretically possible that we end up with two flows. In fact, the probability is close to 0 (negligible) unless there is a lot of jitter in the TCP traffic (still negligible).

**Review by grcevski — APPROVED** [review]
LGTM!
