### PR TITLE
fix(k8s_cache): informer_send_timeout is not enforced

### LINKED ISSUE #1903: k8s_cache: informer_send_timeout is not enforced
marked in [here](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/1886#discussion_r3119977646)

informer_send_timeout is stored on the connection connection, but is never used

### PR DESCRIPTION
**Pull request by itsprdp**
## Summary
The `kubecache` service streams Kubernetes object updates to subscribers over gRPC. Each subscriber connection has a configurable `informer_send_timeout`, the maximum time allowed for a single `Send()` call before the connection is considered stalled and dropped.

**bug**: `informer_send_timeout` was stored on the connection struct but never actually used. `Send()` was called directly with no timeout, so a slow or unresponsive client could block the `goroutine` forever, preventing other events from being delivered.

## PR includes:
1. Adds a regression test - a `blockingStream` fake whose `Send()` blocks indefinitely is wired up, and the test asserts that `handleMessagesQueue` returns within `200ms` when the timeout is `50ms`.
2. Fixes the bug - introduces `sendWithTimeout()`, which:
    - If no timeout is configured, calls `Send()` directly (same behavior as before).
    - If a timeout is configured, runs `Send()` in a `goroutine` and races it against a `time.Timer`. Whichever fires first wins: if the timer  fires, the connection is logged, metered, and dropped.
      The timer is created once outside the loop and reset on each iteration to avoid allocating a new timer per message.

## Validation

- [x] I have read and followed the [contributing guidelines](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/blob/main/CONTRIBUTING.md)
- [ ] If this enhances / fixes / changes a core feature, I have updated the [features documentation](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/blob/main/devdocs/features.md) and [support matrix](https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/blob/main/SUPPORT_MATRIX.md) as needed.

Fixes #1903 

## AI
This contribution was prepared with the assistance of an AI development tool.

### CODE REVIEW

**Review by NimrodAvni78 — APPROVED** [review]
LGTM

File: pkg/kube/kubecache/service/service.go [hunk 1]
```diff
@@ -147,6 +147,11 @@ func (o *connection) On(event *informer.Event) error {
 }
 
 func (o *connection) handleMessagesQueue(ctx context.Context) {
+	var timer *time.Timer
+	if o.sendTimeout > 0 {
```
Comment (mmat11) [inline pkg/kube/kubecache/service/service.go]: should we have a default timeout here if sendTimeout is unset?

File: pkg/kube/kubecache/service/service.go [hunk 2]
```diff
@@ -157,12 +162,52 @@ func (o *connection) handleMessagesQueue(ctx context.Context) {
 			if event == nil {
 				return
 			}
-			if err := o.server.Send(event); err != nil {
-				o.log.Debug("Error sending message. Closing client connection", "clientID", o.ID(), "error", err)
-				o.metrics.MessageError()
+			if err := o.sendWithTimeout(ctx, timer, event); err != nil {
 				return
 			}
 			o.metrics.MessageSucceed()
```
Comment (mmat11) [inline pkg/kube/kubecache/service/service.go]: I think we should update this metric inside sendWithTimeout, for consistency

File: pkg/kube/kubecache/service/service.go [hunk 3]
```diff
@@ -157,12 +162,52 @@ func (o *connection) handleMessagesQueue(ctx context.Context) {
...
 		}
 	}
 }
+
+// sendWithTimeout sends event and, if timer is non-nil, drops the connection
+// when Send blocks longer than o.sendTimeout. Returns a non-nil error whenever
+// the caller should stop processing the queue.
+func (o *connection) sendWithTimeout(ctx context.Context, timer *time.Timer, event *informer.Event) error {
+	if timer == nil {
```
Comment (mmat11) [inline pkg/kube/kubecache/service/service.go]: if we set a default timeout, I think we can avoid this check as timer will never be nil

File: pkg/kube/kubecache/service/service.go
Comment (mmat11) [inline pkg/kube/kubecache/service/service.go:165]: is the sendTimeout supposed to be per-`Send()` or per-batch?

File: pkg/kube/kubecache/service/service.go (hunk 1 above)
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go]: good idea! I'll initialize the default timeout value for connection itself if it's unset so that we can skip the check here

File: pkg/kube/kubecache/service/service.go
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go:165]: It is per-`Send()` and each event would get the full `SendTimeout` window. I'll update the comments to reflect that.

File: pkg/kube/kubecache/service/service.go (hunk 1 above)
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go]: addressed this in https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/1934/commits/f900b5e89379a7da6b60fc5c79d5bc8cf9ae67a9

File: pkg/kube/kubecache/service/service.go (hunk 2 above)
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go]: addressed this in https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/1934/commits/f900b5e89379a7da6b60fc5c79d5bc8cf9ae67a9

File: pkg/kube/kubecache/service/service.go (hunk 3 above)
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go]: addressed this in https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/1934/commits/f900b5e89379a7da6b60fc5c79d5bc8cf9ae67a9

File: pkg/kube/kubecache/service/service.go [hunk 4]
```diff
@@ -157,12 +162,52 @@ func (o *connection) handleMessagesQueue(ctx context.Context) {
...
+			o.log.Debug("Error sending message. Closing client connection", "clientID", o.ID(), "error", err)
+			o.metrics.MessageError()
+			return err
+		}
+		return nil
+	}
+
+	sendErr := make(chan error, 1)
+	go func() { sendErr <- o.server.Send(event) }()
+
```
[the remark this answers is not in the document]
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go:182]: `Send()` doesn't take a context so we can't cancel it. The goroutine exits when gRPC closes the stream after `Subscribe()` returns. `sendErr` is a buffered `chan` so it won't block. Added a comment in https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/1934/commits/9312b28ccfea2e825cc5d7068a44af6ea297858a

File: pkg/kube/kubecache/service/service.go [hunk 5]
```diff
@@ -157,12 +162,52 @@ func (o *connection) handleMessagesQueue(ctx context.Context) {
...
+		if err != nil {
+			o.log.Debug("Error sending message. Closing client connection", "clientID", o.ID(), "error", err)
+			o.metrics.MessageError()
+			return err
+		}
+		return nil
+	case <-timer.C:
+		o.log.Warn("Send timed out. Closing client connection", "clientID", o.ID(), "timeout", o.sendTimeout)
+		o.metrics.MessageTimeout()
+		return context.DeadlineExceeded
```
[the remark this answers is not in the document]
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go:204]: same as https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/1934#discussion_r3151795154

**Review by mmat11 — APPROVED** [review]
lgtm

File: pkg/kube/kubecache/service/service.go [hunk 6]
```diff
@@ -157,12 +166,44 @@ func (o *connection) handleMessagesQueue(ctx context.Context) {
...
+		case <-timer.C:
+		default:
+		}
+	}
+	timer.Reset(o.sendTimeout)
+
+	select {
+	case err := <-sendErr:
+		if err != nil {
+			o.log.Debug("Error sending message. Closing client connection", "clientID", o.ID(), "error", err)
```
Comment (mmat11) [inline pkg/kube/kubecache/service/service.go]: just one last thing: should this be a warn instead?

File: pkg/kube/kubecache/service/service_test.go [hunk 7]
```diff
@@ -129,3 +133,162 @@ func TestRunStopsServerOnContextCancellationWithActiveStream(t *testing.T) {
...
+	}()
+
+	<-sendCalled // wait until Send is blocking before cancelling
+	cancel()
+
+	select {
+	case <-done:
+	case <-time.After(200 * time.Millisecond):
+		t.Fatal("handleMessagesQueue did not return within 200ms after context cancellation")
+	}
```
[the remark this answers is not in the document]
Comment (itsprdp) [reply pkg/kube/kubecache/service/service_test.go:293]: switched this to 2s instead

File: pkg/kube/kubecache/service/service_test.go [hunk 8]
```diff
@@ -129,3 +133,162 @@ func TestRunStopsServerOnContextCancellationWithActiveStream(t *testing.T) {
...
+			go func() {
+				o.handleMessagesQueue(context.Background())
+				close(done)
+			}()
+
+			select {
+			case <-done:
+			case <-time.After(200 * time.Millisecond):
+				t.Fatalf("handleMessagesQueue did not return within 200ms")
+			}
```
[the remark this answers is not in the document]
Comment (itsprdp) [reply pkg/kube/kubecache/service/service_test.go:257]: switched this to 2s instead

File: pkg/kube/kubecache/service/service.go (hunk 6 above)
Comment (itsprdp) [reply pkg/kube/kubecache/service/service.go]: switched it to warn in https://github.com/open-telemetry/opentelemetry-ebpf-instrumentation/pull/1934/commits/0e6ef54cd8b196ef533670922a1946cc54ceb1cc

**Review by grcevski — APPROVED** [review]
LGTM!
