### PR TITLE
Look for the alternative lockdown error message 

### LINKED ISSUE #313: OBI fails to start on AWS Bottlerocket
This seems to be the default choice for the latest EKS cluster deployment configuration 1.33. The error message is as follows:

```
│ ; dst[j++] = hex[(p >> 4) & 0xff]; @ trace_util.h:52                                                                                                                                │
│ 283: (77) r3 >>= 4                    ; R3_w=scalar(smin=smin32=0,smax=umax=smax32=umax32=15,var_off=(0x0; 0xf))                                                                    │
│ 284: (0f) r1 += r3                    ; R1_w=map_value(map=.rodata.str1.1,ks=4,vs=58,off=41,smin=smin32=0,smax=umax=smax32=umax32=15,var_off=(0x0; 0xf)) R3_w=scalar(smin=smin32=0, │
│ 285: (71) r1 = *(u8 *)(r1 +0)         ; R1_w=scalar(smin=smin32=0,smax=umax=smax32=umax32=255,var_off=(0x0; 0xff))                                                                  │
│ 286: (73) *(u8 *)(r10 -54) = r1       ; R1_w=scalar(smin=smin32=0,smax=umax=smax32=umax32=255,var_off=(0x0; 0xff)) R10=fp0 fp-56=???mmmmm                                           │
│ 287: (b7) r1 = 48                     ; R1_w=48                                                                                                                                     │
│ ; *buf++ = '0'; @ tracing.h:38                                                                                                                                                      │
│ 288: (73) *(u8 *)(r10 -51) = r1       ; R1_w=48 R10=fp0 fp-56=??mmmmmm                                                                                                              │
│ ; *buf = (tp->flags == 0) ? '0' : '1'; @ tracing.h:39                                                                                                                               │
│ 289: (71) r2 = *(u8 *)(r7 +48)        ; R2_w=scalar(smin=smin32=0,smax=umax=smax32=umax32=255,var_off=(0x0; 0xff)) R7=map_value(map=grpc_framer_inv,ks=16,vs=64)                    │
│ 290: (15) if r2 == 0x0 goto pc+1      ; R2_w=scalar(smin=umin=smin32=umin32=1,smax=umax=smax32=umax32=255,var_off=(0x0; 0xff))                                                      │
│ 291: (b7) r1 = 49                     ; R1=49                                                                                                                                       │
│ 292: (73) *(u8 *)(r10 -50) = r1       ; R1=49 R10=fp0 fp-56=?mmmmmmm                                                                                                                │
│ ; bpf_probe_write_user(buf_arr + (n & 0x0ffff), &type_byte, sizeof(type_byte)); @ go_grpc.c:878                                                                                     │
│ 293: (79) r2 = *(u64 *)(r10 -40)      ; R2_w=scalar() R10=fp0 fp-40=mmmmmmmm                                                                                                        │
│ 294: (57) r2 &= 65535                 ; R2_w=scalar(smin=smin32=0,smax=umax=smax32=umax32=0xffff,var_off=(0x0; 0xffff))                                                             │
│ 295: (79) r1 = *(u64 *)(r10 -32)      ; R1_w=scalar() R10=fp0 fp-32=mmmmmmmm                                                                                                        │
│ 296: (0f) r1 += r2                    ; R1_w=scalar() R2_w=scalar(smin=smin32=0,smax=umax=smax32=umax32=0xffff,var_off=(0x0; 0xffff))                                               │
│ 297: (bf) r2 = r10                    ; R2_w=fp0 R10=fp0                                                                                                                            │
│ 298: (07) r2 += -108                  ; R2_w=fp-108                                                                                                                                 │
│ 299: (b7) r3 = 1                      ; R3_w=1                                                                                                                                      │
│ 300: (85) call bpf_probe_write_user#36                                                                                                                                              │
│ program of this type cannot use helper bpf_probe_write_user#36
```

The program that hits it first is:

```
error="loading and assigning BPF objects: field BeylaUprobeGrpcFramerWriteHeadersR
```

We should have detected the error to start because of bpf_probe_write_user, but I think we specifically look for helper not found, this is something else, like the helper is there, but we can't use it from this type of program. I think we need to add better detection and failover to not using bpf_probe_write_user.

### PR DESCRIPTION
**Pull request by grcevski**
Apparently on new kernels, when we cannot use `bpf_probe_write_user` we get the following error message: `cannot use helper bpf_probe_write_user` instead of `unknown func bpf_probe_write_user`.

Closes #313

### CODE REVIEW

**Review by rafaelroquetto — APPROVED** [review]
ship it :rocket: !

File: pkg/components/ebpf/tracer_linux.go [hunk 1]
```diff
@@ -197,7 +197,8 @@ func (pt *ProcessTracer) loadTracer(eventContext *common.EBPFEventContext, p Tra
 
 	err := pt.loadAndAssign(eventContext, p)
 
-	if err != nil && strings.Contains(err.Error(), "unknown func bpf_probe_write_user") {
+	if err != nil && (strings.Contains(err.Error(), "unknown func bpf_probe_write_user") ||
+		strings.Contains(err.Error(), "cannot use helper bpf_probe_write_user")) {
```
Comment (mariomac) [inline pkg/components/ebpf/tracer_linux.go:201]: What about just:
```suggestion
	if err != nil && strings.Contains(err.Error(), "bpf_probe_write_user") {
```
The error analysis won't be so precise but it would be more robust against related error messages that could change in the future.

**Review by mariomac — APPROVED** [review]
LGTM!

File: pkg/components/ebpf/tracer_linux.go (hunk 1 above)
Comment (grcevski) [reply pkg/components/ebpf/tracer_linux.go:201]: I'm worried about that side because it can cover other potential errors, maybe we messed up something related to bpf_probe_write_user?

Comment (grcevski) [reply pkg/components/ebpf/tracer_linux.go:201]: What I mean is, imagine we are working on improving and changing something related to the code that uses bpf_probe_write_user and now we passed in a wrong argument. The error message will mention maybe probe_write_user, but it's a development time thing or kernel compatibility. So we won't know it's a failure related to inability to use probe_write_user, but it will be just warned on and we'll load the alternative probes.
